version: '3.8'

services:
  nginx:
    image: nginx:latest
    hostname: nginx
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
      - payment-processor 
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

  backend-01:
    build:
      context: .
      dockerfile: Dockerfile
    # image: josimar-silva/rinha-backend-2025:latest
    hostname: backend-01
    ports:
      - "9999:8080"
    networks:
      - backend
      - payment-processor
    environment:
      - APP_DEFAULT_PAYMENT_PROCESSOR_URL=http://payment-processor-default:8001
      - APP_FALLBACK_PAYMENT_PROCESSOR_URL=http://payment-processor-fallback:8002
      - APP_REDIS_URL=redis://redis:6379
      - APP_SERVER_KEEPALIVE=60
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "160MB"

  backend-02:
    build:
      context: .
      dockerfile: Dockerfile
    # image: josimar-silva/rinha-backend-2025:latest
    hostname: backend-02
    ports:
      - "9999:8081"
    networks:
      - backend
      - payment-processor
    environment:
      - APP_DEFAULT_PAYMENT_PROCESSOR_URL=http://payment-processor-default:8001
      - APP_FALLBACK_PAYMENT_PROCESSOR_URL=http://payment-processor-fallback:8002
      - APP_REDIS_URL=redis://redis:6379
      - APP_SERVER_KEEPALIVE=60
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "160MB"

  redis:
    image: redis:8.0.3-alpine
    hostname: redis
    networks:
      - backend
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "50MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
