name: Docker Builds

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'Cargo.toml'
      - 'Cargo.lock'
  schedule:
    - cron: "0 03 * * 1-5"

jobs:    
  docker:
    runs-on: ubuntu-24.04

    permissions:
      contents: write
      packages: write
   
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get package version
        id: get_version
        run: echo "VERSION=$(cargo pkgid --quiet | cut -d '@' -f 2)" >> $GITHUB_OUTPUT

      - name: Check if version is SNAPSHOT
        id: check_snapshot
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          if [[ "$VERSION" == *"-snapshot"* ]]; then
            echo "IS_SNAPSHOT=true" >> $GITHUB_OUTPUT
          else
            echo "IS_SNAPSHOT=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push production image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            BUILD_VARIANT=prod
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}
            ${{ steps.check_snapshot.outputs.IS_SNAPSHOT == 'false' && format('ghcr.io/{0}:latest', github.repository) || '' }}

      - name: Build and push performance tests image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            BUILD_VARIANT=perf
          tags: |
            ghcr.io/${{ github.repository }}/perf:${{ steps.get_version.outputs.VERSION }}
